<a href="https://colab.research.google.com/github/waqas-ahmd/Colab-Notebooks/blob/main/001-notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


### Variables and Tensors

####Variables and Types

In [5]:
string = tf.Variable("String Variable", tf.string)
integer = tf.Variable(22, tf.int32)
floating = tf.Variable(3.14, tf.float32)
print(string, integer, floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'String Variable'> <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=22> <tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.14>


####Rank and Shape

In [12]:
tensor_1 = tf.Variable([2,3], tf.int32)
tf.rank(tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [13]:
tensor_1.shape

TensorShape([2])

In [15]:
tensor_2 = tf.Variable([[1,2,3],[4,5,6]], tf.int32)
tf.rank(tensor_2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [16]:
tensor_2.shape

TensorShape([2, 3])

####Reshaping Tensors 

In [23]:
tensor_3 = tf.ones([1,2,3], tf.int32)
print(tensor_3)
tensor_3a = tf.reshape(tensor_3,[3,1,2])
print(tensor_3a)
tensor_3b = tf.reshape(tensor_3,[3,-1])
print(tensor_3b) 

tf.Tensor(
[[[1 1 1]
  [1 1 1]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[1 1]]

 [[1 1]]

 [[1 1]]], shape=(3, 1, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]
 [1 1]], shape=(3, 2), dtype=int32)


####Types of Tensors


1.   Variables 
2.   Constants
3.   Placeholders
4.   SpareTensors

